- src/tests/test_service.h
Fixed tests after start_ps_process and all_deps_stopped rename
> Fixed tests

- CONTRIBUTORS
- README.md
- doc/getting_started.md
First attempt, but I think we have a bug. See the XXX in the file.
> A first stab at the getting started guide.

- src/Makefile
Hi,
This is a small fix for *install -s* to work when cross compiled.
> Fixed strip on install for cross compilation

- CONTRIBUTORS
> Adding myself to contributors

- src/igr-tests/environ/setenv.sh
It seems this one didn't occur to me...
> Fix integration tests without dinit installed

- .github/workflows/alpine-latest-aarch64.yml
- .github/workflows/alpine-latest-armv6.yml
- .github/workflows/alpine-latest-armv7.yml
More orderly CIs
Remove unwanted configure (its handled by `make` command)
> CI: Refactor ARMs CI

- .cirrus.yml
- configs/mconfig.FreeBSD
Hello.
After a long time, finally, an automated mechanism was built to test Dinit on a BSD :)
**An important note: before merging this PR, be sure to add cirrus-ci for the dinit repository according to the guide here: https://cirrus-ci.org/guide/quick-start/**
Test `dinit` on `FreeBSD`
> CI: Initial FreeBSD ci [Need manual action!]

- .github/workflows/macos-latest-amd64.yml
Hi.
Now we can test the functionality of dinit on Mac OS/darwin (on every commit/PR)!
MacOS CI
> CI: MacOS CI!

- .cirrus.yml
> CI: improve FreeBSD CI!

- src/tests/cptests/Makefile
> Fix broken PATH for includes in `fuzz` make target

- src/tests/cptests/Makefile
> Make sure `prepare-incdir` runs in `fuzz` make target

- doc/linux/DINIT-AS-INIT.md
> doc: a Minor update about using Dinit as system init

- .cirrus.yml
> CI: Upgrade to FreeBSD 12.4 in cirrus-ci

- doc/manpages/dinit-service.5.m4
- src/igr-tests/basic/sd/basic
- src/igr-tests/chain-to/sd/part1
- src/igr-tests/chain-to/sd/part2
- src/igr-tests/chain-to/sd/part3
- src/igr-tests/chain-to/sd/part4
- src/igr-tests/chain-to/sd/part5
- src/igr-tests/environ/sd/checkenv
- src/igr-tests/environ/sd/setenv1
- src/igr-tests/ps-environ/sd/checkenv1
- src/igr-tests/ps-environ/sd/checkenv2
- src/igr-tests/ps-environ/sd/checkenv3
- src/igr-tests/ps-environ/sd/checkenv4
- src/igr-tests/restart/sd/basic
- src/igr-tests/svc-start-fail/sd/bad-command
- src/igr-tests/var-subst/sd/checkargs
- src/includes/load-service.h
Also, document the behavior. Previously, there was nothing actually specifying what the default is.
Fixes https://github.com/davmac314/dinit/issues/168
> Make services automatically restart on stop by default

- src/igr-tests/meson.build
> meson: Add new `environ2` igr test

- configure
> configure: Some improvments

- .cirrus.yml
- .github/workflows/meson_ci.yml
- .github/workflows/regular_ci.yml
> CI: Fix workflows run for unrelated changes

- src/igr-tests/meson.build
This commit just add it to src/igr-tests/meson.build
> meson: `before-after2` igr-test

- src/igr-tests/meson.build
> meson: `log-via-pipe` and `catlog` igr-tests

- contrib/shell-completion/bash/README
- contrib/shell-completion/bash/dinitctl
> contrib: Add dinitctl bash-completion

- .cirrus.yml
Also it tests configure script which is good I think.
Regards
> CI: New ci which focus on security hardening

- contrib/sysv-compat/40-dinit
- contrib/sysv-compat/README
See `contrib/sysv-compat/README` for more info.
> contrib: New `sysv-compat` section

- configure
> configure: Some fixes around adding $CXXFLAGS to $LDFLAGS if lto supported

- .cirrus.yml
> CI: Don't use matrix when there is no more than 1 task

- src/meson.build
- src/tests/cptests/meson.build
- src/tests/meson.build
> meson: Add new "settings.cc" to sources list

- src/dinitctl.cc
With this change we can eliminate the "SERVICESTATUS vs SERVICEEVENT" race.
Fixes #363
> dinitctl: Handle the "SERVICEEVENT vs SERVICESTATUS" race 

- .github/workflows/meson_ci.yml
> CI: Don't skip meson workflow on manual dispatch

- src/shutdown.cc
The #333 came to my mind and I checked the `shutdown.cc` code to make sure that's OK and It's not.
> shutdown: Select respective action on halt and soft-reboot utilities

- src/dinit.cc
The new features are "capabilities", "io-priority" and "oom-score-adjust"
> dinit: Mention new added features in "--version" argument output

- doc/manpages/shutdown.8.m4
- src/shutdown.cc
As per https://github.com/davmac314/dinit/issues/439.
> Pass shutdown type to shutdown hook script

- src/Makefile
- src/includes/dinit-util.h
- src/includes/load-service.h
- src/includes/proc-service.h
- src/load-service.cc
This is useful for detecting invalid capabilties in dinitcheck.
Fixes #417 
> load-service: Validate capabilities

- meson.build
> meson: Fix too long lines

- contrib/freebsd-rc/README
Hi! I have installed dinit on FreeBSD again!
> Update FreeBSD install instructions
