README.md, doc/manpages/dinitctl.8.m4, src/dinitctl.cc
This removes the need to use --system when dinitctl runs as root.
=> Adding root check on default control socket

src/Makefile
This fixes the following error while compiling:
```
make -C src all
make[1]: Entering directory '/builddir/dinit-0.7.0/src'
g++  -o mconfig-gen mconfig-gen.cc -Wl,-z,relro -Wl,-z,now -Wl,--as-needed    
g++ -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Os -Wall -fno-rtti -fno-plt -flto -MMD -MP -Iincludes -Idasynq -c dinitctl.cc -o dinitctl.o
dinitctl.cc:26:10: fatal error: mconfig.h: No such file or directory
26 | #include "mconfig.h"
|          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:48: dinitctl.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/builddir/dinit-0.7.0/src'
make: *** [Makefile:4: all] Error 2
```
Let me know if this is {in}correct since I have never formally learned how makefiles work.
=> Fix makefile.

doc/manpages/dinit-service.5.m4, src/igr-tests/chain-to/record-param.sh, src/igr-tests/chain-to/run-test.sh, src/igr-tests/chain-to/sd/part3, src/igr-tests/chain-to/sd/part4, src/igr-tests/chain-to/sd/part5, src/includes/load-service.h, src/service.cc
`always-chain` alters behavior of `chains-to` property forcing the chained service to always start on termination of a service.
=> Add always-chain option

doc/manpages/Makefile, doc/manpages/shutdown.8.m4, src/Makefile
Symlinks are more obvious/easier to track than hardlinks and as far as I can tell there is no disadvantage to using them.
Additionally, provide a "poweroff" command alias. This is to improve compatibility with e.g. `elogind` which internally calls it when you try to shut down the system via `loginctl`.
=> use symlinks instead of hardlinks for command aliases, provide "poweroff" alias

configs/mconfig.Darwin, configs/mconfig.Linux, configs/mconfig.Linux.sh, src/Makefile, src/tests/Makefile, src/tests/cptests/Makefile
It is common convention that compiler flags are passed during linkage, providing increased robustness/convenience when e.g. cross-compiling or in some cases of LTO builds.
=> Also pass CXXOPTS when linking

CONTRIBUTORS, doc/manpages/dinitctl.8.m4, src/control.cc, src/dinitctl.cc, src/igr-tests/environ/run-test.sh, src/igr-tests/environ/sd/setenv1, src/igr-tests/environ/sd/setenv2, src/igr-tests/environ/sd/setenv3, src/igr-tests/environ/setenv.sh, src/includes/control-cmds.h, src/includes/control.h
This is a pretty rough draft, mostly to get comments right now.
It adds a new `setenv` command to `dinitctl`. The command can take any number of variables, either as variable names alone (in which case the value is retrieved from the environment `dinitctl` is called in) or in the format `FOO=bar` (which encodes the value).
Limitations:
- length of the name + value + `=` is limited to 1024 minus protocol overhead characters (do we want to bother with a chunked protocol that would let one pass longer vars? i'm leaning towards not, as it seems to be of limited use and likely a sign of doing something terribly wrong)
Fixes https://github.com/davmac314/dinit/issues/43
=> command to set a variable in activation environment

doc/manpages/dinit.8.m4, doc/manpages/dinitctl.8.m4, src/dinit.cc, src/dinitctl.cc, src/igr-tests/environ/checkenv.sh, src/igr-tests/environ/run-test.sh, src/igr-tests/environ/setenv.sh
This brings two ideas; they are implemented separately, and I am myself not entirely sure if they're good ideas, so I want to raise it here to get some feedback.
1) Both `dinitctl` and `dinit` now read the environment variable `DINIT_SOCKET_PATH` and use it preferentially to determine what the control socket path is. Additionally, `dinit` exports the socket's path into the environment under that name, canonicalized/made absolute. The idea is that when you call `dinitctl` within the service environment, you don't have to worry about passing the socket path (the service may not even know the socket path otherwise, since the user who launches the `--user` instance is in charge of that). However, I'm not sure if both `dinit` and `dinictl` should read the var. Maybe only `dinitctl` should, and …
=> some dinitctl socket management enhancements

doc/manpages/dinit-service.5.m4, doc/manpages/dinit.8.m4, doc/manpages/dinitcheck.8.m4, src/options-processing.cc
The /etc directory is a directory for system configuration files.
The .config directory in most Linux systems nowadays mirrors this.
Explicitly do not follow XDG_CONFIG_HOME as changing that is of questionable value and the XDG base directory spec is overly complicated and has various quirky parts. However, IME most users appreciate having config files in a separate location and .config is where a lot of software stores these nowadays, so being consistent with that should be a good thing.
One may consider the location being in a hidden directory a potential issue, I think it's not really a problem since in most cases one wants to have this kind of stuff out of the way (dealing with service files is something one typically does rarely in production) and in other cases it should not be an …
=> Default to .config for user services directory

.github/workflows/alpine-latest-aarch64.yml, .github/workflows/alpine-latest-armv6.yml, .github/workflows/alpine-latest-armv7.yml, .github/workflows/debian-bullseye-amd64.yml, .github/workflows/debian-bullseye-i386.yml
=> CI: Enable integration tests on all test suites

doc/linux/services/filesystems.sh
devpts and shm are already being mounted in `early-filesystems.sh`
=> don't mount devpts and shm again

.github/workflows/alpine-latest-aarch64.yml, .github/workflows/alpine-latest-armv6.yml, .github/workflows/alpine-latest-armv7.yml
Hello.
`run-on-arch` used to compile & test Dinit on arm(s) platform.
This PR updates runs-on-arch to version 2.2.0. The most important feature of this additional version is `$github_env`, which will be useful in the future.
=> CI: Update `run-on-arch` from `v2` to `v2.2.0`

CONTRIBUTORS, doc/manpages/dinit.8.m4, src/dinit.cc
Hi!
This issue is discussed in #69 (although we need to talk more about it now). This time, I decided to add Add support for "Loading any service with dinit on system manager mode" with my c++ knowledge.
Fix #69
Add support for loading a service at boot time. its good for create `rescue` service and boot it if necessary also its good for have SystemD target-like services.
- ~~Pay attention to issue #74 and use `string_ha` instead of `string` if necessary (I have to look into it more).~~ **Its not necessary**
=> Add support for "Loading any service with `dinit` on `system manager mode`"

.github/workflows/alpine-latest-aarch64.yml, .github/workflows/alpine-latest-armv6.yml, .github/workflows/alpine-latest-armv7.yml, .github/workflows/debian-bullseye-amd64.yml, .github/workflows/debian-bullseye-i386.yml
=> CI: some ci cleanup

src/tests/Makefile
This eliminates a build race when envtests would be run before it is built.
=> Add missing tests make dependency

src/tests/cptests/Makefile
because fuzz target not runned by top level make; we need to create mconfig.h manually.
Fixes #91
=> Create mconfig.h for fuzzing

.github/workflows/ubuntu-latest-amd64-fuzzer.yml, .github/workflows/ubuntu-latest-amd64-minifuzzer.yml
Provide auto fuzzer for dinit project on github CI
Fixes #90 
=> CI: Fuzzer for dinit!

doc/linux/services/modules.sh
Use `grep -E` instead of `egrep` in `/doc/linux/services/modules.sh` file
> Why?
because GNU grep developers in [GNU grep 3.8 release notice](https://lists.gnu.org/archive/html/info-gnu/2022-09/msg00001.html) said:
>  The egrep and fgrep commands, which have been deprecated since
release 2.5.3 (2007), now warn that they are obsolescent and should
be replaced by grep -E and grep -F.
=> Linux services example: modules.sh: Use `grep -E` instead of `egrep`

src/control.cc, src/dinitctl.cc, src/includes/control.h, src/includes/service-constants.h, src/includes/service.h, src/service.cc, src/tests/tests.cc
I have an issue where I need to restart pipewire and its dependents (`pipewire-pulse`, `wireplumber`).
With this change I can restart the `pipewire` service which will stop all the dependents and then restart pipewire which results in the dependents being started again since its made sure that all dependents of pipewire have `restart = true`.
Not sure if the check for `!pinned_started` is correct, but it seems logical to now allow restarts if the dependent is pinned started.
Another way would be to allow `--force` again for restarts, but that leaves the services in a bad state if a dependent doesn't restart on its own.
=> Allow restart of services if all dependents restart automatically

doc/linux/services/rootfscheck.sh
=> Example linux services: rootfscheck.sh: Fix #117

src/load-service.cc
The previous code would remain errno to be set after trying bad service directories (despite having encountered a valid one later), which would result in nonsensical error messages outside that path.
=> Clear errno after trying multiple service dirs

src/Makefile, src/tests/Makefile
Seems like in some cases `/src/tests/envtests` and `/src/dinit-monitor` not removed by `make check` command. This patch fix those issues.
Regards
`Signed-off-by: Mobin 'hojjat' Aydinfar <mobin@mobintestserver.ir>`
=> make: Some fixes to `make clean`

src/tests/meson.build
Title is enough for commit goal but I have a question about `loadtests` error. When `test-services` directory is not available, `loadtests` print this to `stderr`: `libc++abi: terminating due to uncaught exception of type service_not_found`, This is normal?
`Signed-off-by: Mobin 'hojjat' Aydinfar <mobin@mobintestserver.ir>`
=> meson: Fix `loadtests` on meson builds

src/tests/Makefile, src/tests/cptests/Makefile
As things are, user-passed flags override the sanitizer options that are used for tests. The UBSan sanitizer has a minimal runtime option, which can be used in production due to minimal overhead while still printing reasonable messages. However, this minimal runtime is not compatible with ASan, which is used for tests by default, therefore it is necessary to disable this minimal runtime for those files.
Unless SANITIZEOPTS are passed last, the potential minimal-runtime option passed from flags used for the rest of the build may result in failed test builds when SANITIZEOPTS contain ASan. Even if passed last, one still gotta disable the minimal runtime inside of SANITIZEOPTS, but that is something the user can control.
=> make: pass SANITIZEOPTS last

src/Makefile, src/igr-tests/Makefile
Hi!
"Sometimes we forget when add a new feature be careful about `make clean` command and add new things to that. It's a example."
`src/igr-tests/check-lint/output.txt`, `src/igr-tests/no-command-error/dinit-run.log` and `src/igr-tests/var-subst/args-record` not removes by `make clean` Also when `SHUTDOWN_PREFIX` is used, its have a same story. This patch fix this these things.
P.S: I working on packaging `dinit` for Debian and I have a plan to add it to Debian official repos. These things finded by `debuild -us -uc` command.
Regards
=> Make: igr-tests and src/: Some cleanup for `make clean`

.cirrus.yml
=> CI: Use `matrix` for more clean FreeBSD CIs

src/dinit.cc
Easiest PR, ever. :)
Fixes #147 
Tried it locally on my OpenWrt router, works exactly as expected.
```
root@FriendlyWrt /s/o/dinit (master)# /etc/init.d/dinit restart
root@FriendlyWrt /s/o/dinit (master)# ls /var/log
caddy.dinit.log  caddy.log  dinit.log  lastlog  log.nmbd  log.smbd  mysql  php8-fpm.log  rclone  samba  tor  wtmp  www.access.log
root@FriendlyWrt /s/o/dinit (master)# tail -f /var/log/dinit.log
dinit: Starting system
dinit: service caddy started.
dinit: service boot started.
^C⏎
root@FriendlyWrt /s/o/dinit (master) [SIGINT]# ps -ef | grep dinit
29095 root      0:00 /sbin/dinit -d /sdcard/dinit.d --log-file /var/log/dinit.log
```
=> Swap AND to OR, fix `--log-file` when in system mode.

.cirrus.yml
Hi
Don't run cirrus-ci when something like `README.md` changes. (Changes already made for Github CI in https://github.com/davmac314/dinit/pull/132)
Regards
=> CI: Don't run cirrus-ci when something like `README.md` changes

configure
Hello
Improve `configure` script.
Regards
=> configure: Don't use `findcxx()` function

doc/manpages/dinitctl.8.m4, src/dinitctl.cc
The is-active command makes dinitctl return 0 when the given service is currently active, and 1 in any other scenario. The is-failed command makes it return 0 when the given service has failed to start and is currently stopped, and 1 in any other scenario. The service not existing and so on counts as non-success for both commands.
The purpose of these is to use them in scripts, as parsing status output is clunky. In general it is enough to pass --quiet and just check the status code, but both commands also print the current service status (and nothing else) if in default verbose mode.
It is similar to the same-named commands in `systemctl`.
=> dinitctl: add is-active and is-failed commands

.gitignore, doc/manpages/dinit-service.5.m4, src/dinitcheck.cc, src/igr-tests/Makefile, src/igr-tests/environ/checkenv.sh, src/igr-tests/environ/run-test.sh, src/igr-tests/environ/sd/checkenv, src/igr-tests/environ2/checkenv.sh, src/igr-tests/environ2/env-dinit, src/igr-tests/environ2/env-service, src/igr-tests/environ2/run-test.sh, src/igr-tests/environ2/sd/checkenv, src/igr-tests/igr-runner.cc, src/igr-tests/var-subst/checkargs.sh, src/igr-tests/var-subst/run-test.sh, src/igr-tests/var-subst/sd/checkargs, src/includes/dinit-env.h, src/includes/load-service.h, src/includes/service.h, src/load-service.cc, src/run-child-proc.cc, src/tests/loadtests.cc, src/tests/test-services/t2
The previous behavior did not substitute env-file variables at service load, because it could only see the environment available to dinit process. This changes that, and env-files are instead loaded during service load, and all variables are substituted.
The vars set up during process call are not exposed here. These would have limited usability in any case and would significantly complicate the whole thing.
I am putting this here to get comments. The code is not necessarily good/clean, e.g. dinitcheck is not properly implemented at this point, and there are no tests yet. I mostly want to know if continuing with this approach is okay. The referenced issue from @Duncaen also talks about implementing basic variable substitutions, I still gotta think about those. I think a well defined …
=> substitute env-file in service files at load

.github/workflows/regular_ci.yml
It's helps us to avoid these things in CI logs:
```
...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
...
```
Regards
`Signed-off-by: Mobin "Hojjat" Aydinfar …
=> CI: Use `DEBIAN_FRONTEND=noninteractive` in Debian CI(s)

src/baseproc-service.cc
We need to treat NONE (which is the default) the same as LOGFILE, so that we get a default /dev/null target. Otherwise, it is treated as BUFFER by default, which is undesirable, as processes will suddenly start hanging as soon as they run out of buffer space.
=> baseproc-service: fix default log target for none-logged services

BUILD, BUILD_MESON, build/Makefile, build/tools/mconfig-gen.cc, configure, doc/manpages/dinit-service.5.m4, meson.build, meson_options.txt, src/run-child-proc.cc
This is practically portable (exists on Linux, BSDs, Solaris, etc) despite not being POSIX, so enable it unconditionally without extra checks. It can still be disabled explicitly if needed.
Fixes https://github.com/davmac314/dinit/issues/151
=> run-child-proc: initialize supplementary groups for named run-as

.github/workflows/meson_ci.yml
Previously Meson based CI hosted on SourceHut. That was great but sr.ht doesn't have good support for integrating with GitHub due to sunset of 'dispatch.sr.ht`. So I moving my workflows from there to GitHub for better Integration.
These are designed to be in main repo (davmac314/dinit) but these aren't running by default. These will be ran when a PR in main repo has "meson" label.
Regards
=> CI: Meson CI(s) on GitHub.

doc/manpages/dinit-service.5.m4, src/includes/load-service.h, src/includes/proc-service.h, src/load-service.cc, src/run-child-proc.cc
Hi!
Some new options in services: `logfile-permissions`, `logfile-uid`, `logfile-gid`.
ToDo
It's mostly ready but We need to discuss about some things:
Best regards
Fixes #193
=> dinit-service: `logfile-permissions`, `logfile-uid`, `logfile-gid` opts

.cirrus.yml, .github/workflows/meson_ci.yml, .github/workflows/regular_ci.yml
=> CI: Minor improvements

.gitignore, src/igr-tests/igr_functions.sh
Hi.
Changes:
- Some minor fixes
- Don't include obsolete temp files in `.gitignore`
- Don't send test logs into system syslog
Regards
`Signed-off-by: Mobin "Hojjat" Aydinfar <mobin@mobintestserver.ir"`
=> Igr-tests: Minor fixes and improvements

configure
Hello. Changes:
1. `sub_warning()` is combined with `warning()` for better usage
2. Some new short options (`-h`, `-q`, `-c`)
3. Fixes "TEST_CXXFLAGS_EXTRA" which got ignored
4. Fixes unnecessary forking for writing into mconfig
5. `--clean` renamed to `--clear` (I think it's better now)
=> configure: Some minor fixes and improvements

doc/manpages/dinitctl.8.m4, src/control.cc, src/dinitctl.cc, src/includes/control-cmds.h, src/includes/control.h, src/includes/load-service.h, src/tests/cptests/cptests.cc, src/tests/proctests.cc, src/tests/test_procservice.h
This adds support for sending signals to services, as I consider it a generally useful feature and implemented it with hacky scripts parsing the output of `dinitctl status $service` in the past. Many services use signals for reloading configuration files and/or enabling/disabling specific runtime features. The feature is currently requested by #134 and @davmac314 commented that
> it's something that is planned
As this would be my first contribution to the project I appreciate any feedback. I'm willing to implement changes/improvements.
I've tried to follow contribution guidelines. Tests are still missing. I will add them if the feature is generally considered accepted.
Open questions/limitations:
- Should signalling be moved from `control.cc` directly as a feature into the (decedents of …
=> Feature signal support

src/dinit.cc
I think it's useful to allow checking it via `dinit -v`
=> dinit: show in `--version` if dinit was compiled with initgroups

src/meson.build
Fixes meson CI failure due to 788d65f commit
=> meson: Include `option-processing` for compiling dinitctl

src/igr-tests/environ2/run-test.sh
=> igr: environ2: Ignore `unset` errors for `UID`, `GID`

src/includes/load-service.h
Hi.
In the past, the dinitctl command to start that service would just hang and dinit would mark that service as STOPPED without any reason in its reports.
=> load-service: throw an error if the "consumer" service is its own consumer

configure
This option used by many package build systems for ensure they can create debug related packages.
=> configure: `--disable-strip` option

src/dinit-env.cc, src/dinit.cc, src/includes/dinit-env.h, src/load-service.cc
Try to make less confusion on failure cases like #238  
It makes more sense. Note failure in reading `/etc/dinit/environment` isn't a hard error.
=> dinit: Treat failure in reading env-file as hard error

src/control.cc, src/dinit-monitor.cc, src/dinitctl.cc, src/includes/control-cmds.h, src/includes/control-datatypes.h, src/includes/control.h, src/includes/dinit-client.h, src/includes/service-constants.h, src/shutdown.cc, src/tests/cptests/cptests.cc
Hey, I've started to work on getting the datatypes used in the socket communication unified. (See #179 ) The types are now defined in control-datatypes.h .
The process led to a little bit of refactoring of the control commands in control-cmds.h .
Before I go on with the other datatypes and control commands I would appriciate some feedback if you have the time @mobin-2008 or @davmac314 .
=> Unify socket datatypes

doc/manpages/dinit-monitor.8.m4, src/dinit-monitor.cc, src/includes/control-cmds.h
I've refactored dinit-monitor a little bit to execute commands for the initial service state. Also added options to specify strings to be substituted per service state.
=> dinit monitor execute command for initial status

.gitignore, CONTRIBUTORS, doc/manpages/dinit-service.5.m4, doc/manpages/dinit.8.m4, doc/manpages/dinitcheck.8.m4, src/igr-tests/igr-runner.cc, src/igr-tests/xdg-config/basic.sh, src/igr-tests/xdg-config/config/dinit.d/basic, src/igr-tests/xdg-config/run-test.sh, src/options-processing.cc
Dinit's default user service directory is `$HOME/.config/dinit.d/`. It does not respect / comply with the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). This PR adds `$XDG_CONFIG_HOME/dinit.d/` as an additional default user service directory (alongside `$HOME/.config/dinit.d/` for backwards compatibility).
When searching for service definition files as a user instance, the following cases are possible:
- no `$XDG_CONFIG_HOME` is set
-> only search `$HOME/.config/dinit.d/`
- `$XDG_CONFIG_HOME` is set to `$HOME/.config`
-> `$HOME/.config/dinit.d/` will be searched twice
- `$XDG_CONFIG_HOME` is set to a custom directory
-> search `$XDG_CONFIG_HOME/dinit.d/` and then `$HOME/.config/dinit.d/`
As far as I can tell, this should …
=> Add $XDG_CONFIG_HOME/dinit.d/ to default user service directories

configure
Previously, All flags get checked through try_cxx_argument() which can return 1 on unsupported flag and its return should be ignored but it's made into confusion.
See https://github.com/davmac314/dinit/issues/281 for a example.
This commit creates a new function that will ignore try_cxx_argument() return by default and this commit replaces all uses of try_cxx_argument() on optional flags with this new function.
Fixes #281 
=> configure: use `try_optional_cxx_argument()` when flag is not required for less confusion

configure
=> configure: Fix "parameter is not set" failure on setting "LDFLAGS_BASE"

doc/manpages/dinitctl.8.m4, src/dinitctl.cc, src/igr-tests/before-after2/run-test.sh
Not sure if this change is good, but it solves the inconsistency mentioned in #295.
Maybe we should mention both "regular" and "need" in the `dinitctl` man page?
fixes #295.
=> rename "regular" in `dinitctl add-dep` to "need"

doc/manpages/meson.build, src/meson.build
Self-explanatory.
This will make the meson build 1:1 with the Makefile build, since the Makefile build already has poweroff but not meson.
=> meson.build: add poweroff bin

.github/workflows/meson_ci.yml
The MacOS version used in GitHub actions is upgraded. This version does block installing a system-wide program through "pip". Just use "brew" for installing meson.
(This PR also removes install step for ninja, because it will be installed in meson
installation process)
`Signed-off-by: Mobin Aydinfar <mobin@mobinttestserver.ir>`
=> CI: Use "brew" for installing meson in meson-based workflow

.github/workflows/meson_ci.yml
We recently bumped required version of Meson to 0.63 and debian bullseye doesn't have it.
=> CI: Upgrade Debian workflow to bookworm

doc/manpages/meson.build, src/meson.build
Commits are self-explanatory.
There is a fix around shutdown executables and a small fix about using values from root meson.build in addition of man-pages fixes.
=> meson: Some fixes around shutdown building

contrib/freebsd-rc/README, contrib/freebsd-rc/tree/etc/dinit.d/boot
I installed dinit on FreeBSD again. The script in README should now do everything needed to install dinit to run under rc.d.
Related future plan:  
to create a port: https://docs.freebsd.org/en/books/porters-handbook/quick-porting/
=> Tweak FreeBSD install instruction

doc/manpages/dinit-service.5.m4
Self-explanatory.
I Just replaced "b" with "B" :)
=> doc/manpages: Fix missing highlight mark for "Triggered" service type

src/shutdown.cc
It was a bug that shutdown executable only checked "reboot" string to find out this should be a reboot or normal shutdown.
Regression: It's not, because it was broken from the beginning.
=> shutdown: Respect "SHUTDOWN_PREFIX" for reboot util check

doc/manpages/dinit-service.5.m4, src/includes/load-service.h, src/tests/loadtests.cc, src/tests/test-services/t3
A few alternative options are possible (such appending the newline literally and handling them in `read_setting_value` , or translating it into a space) but this is likely what most people, coming from the shell, expect.
Closes: https://github.com/davmac314/dinit/issues/291
=> Add newline escaping support

src/igr-tests/Makefile, src/igr-tests/igr-runner.cc, src/igr-tests/igr.h, src/igr-tests/meson.build
Hi.
Summary of changes:
1. `igr_dinit_socket_path` is removed and `socket_path` should be prepared for each test to avoid any race condition instead.
2. Added ability to run a single test to support meson tests wrapper.
3. Any path from source (such as expected results) should use `igr_base_basedir` which is set by meson (default values are for Make based runtime).
For meson igr-tests, I decide to stay with manual list but it's now really simple to add new test, Just add name of test to a list and everything will work out-of-box.
Fixes #302
=> meson: Use `igr-runner` for igr-tests

src/igr-tests/igr-runner.cc
To avoid such case:
...
Test run finished.
Passed: 26
Failed: 0make[2]: Leaving directory '/__w/dinit/dinit/src/igr-tests' make[1]: Leaving directory '/__w/dinit/dinit/src'
...
=> igr-runner: Make sure "Failed" line ends with a newline

src/control.cc, src/tests/cptests/cptests.cc, src/tests/test-includes/dinit.h
[CWE-835: Loop with Unreachable Exit Condition ('Infinite Loop')](https://cwe.mitre.org/data/definitions/835.html)
Sending garbage data and then closing the connection could lead into out-of-memory. Because after closing the connection, Dinit will stuck in `(rbuf.get_length() >= chklen)` while loop and then the outbuf buffer is used because the connection fd is not available anymore. This triggers the OOM detector in the fuzzer and can result in segfault when Dinit is used as init of system.
It's mostly harmless because triggering it requires root or particular user (the user who starts dinit) access. See https://github.com/davmac314/dinit/blob/master/doc/SECURITY
Firstly detected in https://github.com/davmac314/dinit/actions/runs/7233843212
`Signed-off-by: Mobin Aydinfar …
=> control: Don't call process_packet() when bad_conn_closed is set

.github/workflows/regular_ci.yml
Looks like GitHub now uses arm64 machines for MacOS workflows.
=> CI: Fix grammar and mark MacOS workflow as ARM64 not x86_64

src/tests/cptests/Makefile
We already have `parent_objs` built in `../` directory with exactly same compiler flags. So why we don't use them in cptests also instead of building them again?
This also should improve build time.
=> cptests/Makefile: Don't rebuild test objects that were built by primary tests

src/igr-tests/Makefile
It should be there, I guess.
I was testing Dinit on NetBSD with `./configure CXX=clang++ CPPFLAGS="-DDASYNQ_HAVE_KQUEUE=1"` (and it was really awesome) that found out the `CPPFLAGS` is not applied in igr-runner compile process.
=> igr-tests/Makefile: Include "CPPFLAGS" in igr-runner compile process

BUILD_MESON, configure, doc/manpages/Makefile, doc/manpages/meson.build, doc/manpages/shutdown.8.m4, meson_options.txt, src/Makefile, src/control.cc, src/dinit.cc, src/includes/service-constants.h, src/meson.build, src/shutdown.cc
this commit adds initial support for `soft-reboot` command to `shutdown`, which is similar to [systemd's soft-reboot](https://www.freedesktop.org/software/systemd/man/latest/systemd-soft-reboot.service.html), but without root switching.
Early services need to be idempotent for soft-reboot to work properly.
---
~~Updated: added an argument `--ignore-sys-args` to ignore kernel args, which would be added automatically in soft-reboot `execv`.~~
~~Updated: filtered out "single" argument~~
Updated: The re-`execv`-ing retains boot-time parameters to simplify the code and is consistent with systemd's soft-reboot behavior.
=> add soft-reboot

.github/workflows/meson_ci.yml
Same as #355 but for `meson_ci.yml`
=> CI: meson_ci.yml: Mark MacOS as aarch64 not amd64

src/dinitctl.cc
Looks like a copy-pasta error :)
=> dinitctl: Fix wrong app name in "--services-dir" not found error message

src/includes/load-service.h
Commits are self-explanatory. Second one was found when I checked all options for correct error handling.
=> load-service: Minor fixes around setting handling

src/dinitctl.cc
An empty argument means that something should be there but it's not there for some reason (for example an empty shell variable is used). dinitctl should exit on empty argument.
Fixes #365 
=> dinitctl: Error on empty arguments

.github/workflows/meson_ci.yml, .github/workflows/regular_ci.yml
This is more useful.
Fixes #378 
=> CI: Replace Alpine ARM targets with a amd64 one

src/dinitcheck.cc
dinit's behavior depends on PATH environment if a service contains command with non-absolute executable path. dinitcheck may not even find correct executables in this case.
Such services may lead to security problems, systemd has been searching executables only in compilation-time specified paths. As similar features do not exist in dinit and aren't very meaningful, we just warn about dangerous usage.
References: https://www.man7.org/linux/man-pages/man5/systemd.service.5.html#COMMAND_LINES
=> dinitcheck: warn about non-absolute executable path

doc/manpages/dinit-service.5.m4, doc/manpages/dinit.8.m4, doc/manpages/dinitctl.8.m4, src/dinitcheck.cc, src/igr-tests/igr-runner.cc, src/igr-tests/svc-arg/checkarg.sh, src/igr-tests/svc-arg/sd/checkarg, src/igr-tests/svc-arg/sd/checkarg2, src/igr-tests/svc-arg/sd/checkarg3, src/igr-tests/svc-arg/sd/checkarg4, src/igr-tests/svc-arg/sd/checkarg5, src/includes/load-service.h, src/load-service.cc, src/tests/loadtests.cc
The argument is a part of the full service name always. Therefore, each argument instantiation is a separate instance of the service, with separate loading.
The following cases are supported:
1) passing the argument to any `dinitctl` command that takes an a service name
2) dependencies with an argument
2) using the argument in any context that does variable substitution
3) using the argument in dependency arguments (performing a restricted version of variable substitution)
documentation is updated, load+integration tests are updated/added
while at it, i found that depends-ms.d was being parsed wrong (it was never reading the dir) so i fixed that too
=> add support for passing arguments to services

src/control.cc, src/dinitctl.cc
Just something I ran into while browsing the code for libdinitctl. This new protocol does not seem to be used at all yet because the protocol version has not been incremented to 5, but might as well not forget.
=> Fix status filling for new protocol

doc/manpages/dinit-monitor.8.m4, doc/manpages/dinitctl.8.m4, src/control.cc, src/dinit-monitor.cc, src/dinitctl.cc, src/igr-tests/environ/setenv.sh, src/igr-tests/igr-runner.cc, src/includes/control-cmds.h, src/includes/control.h, src/includes/dinit-env.h, src/tests/cptests/cptests.cc
This implements a protocol that lets a connection to the control socket listen on changes in the global environment issued by `dinitctl setenv`. This opens up a range of possibilities - such as special services that trigger other services when an environment variable appears.
It also implements a `dinit-monitor` environment watching mode as a proof of functionality, though likely not acceptable as is (likely at least the `string_view` will need getting rid of?)
I intentionally did not implement things like protocol checking and whatnot yet since I want your feedback first.
I should probably also change the protocol a bit - at very least, the envevent should contain information about whether the envvar is newly created or if it overwrites a previous one.
Let me know what you think :)
=> Implement listening on activation environment changes

doc/manpages/dinit-service.5.m4, src/igr-tests/igr-runner.cc, src/igr-tests/svc-arg/checkarg.sh, src/igr-tests/svc-arg/sd/checkarg, src/igr-tests/svc-arg/sd/env-foo, src/igr-tests/svc-arg/sd/inc-foo, src/includes/load-service.h, src/load-service.cc
This changes 3 things:
1) The meta-commands now resolve the service argument. This is useful to set different fields depending on the argument value (by including separate per-arg-value file)
2) The env-file path itself performs minimal expansion (so you can include different env-files depending on the value of the argument)
3) Make it possible to have a service that only optionally takes an argument by using the substitution syntax that takes default values instead of always erroring. The syntaxes without a value will still error.
=> Service argument enhancements

doc/manpages/dinit.8.m4, src/dinit.cc
In some setups it makes sense to launch dinit with `--auto-recovery` and handle boot failures purely via the `recovery` service always. Likely missing some stuff etc but this implements the feature in a hopefully proper way.
Fixes #387.
=> Implement auto-recovery

CONTRIBUTORS, src/includes/service.h
It was adding `line X` directly after the service file path without any kind of separation. As an example the following:
```
dinit: Error in service description for 'early-test' (file /etc/dinit.d/early-testline 1): badly formed line.
dinit: Error in service description for 'early-test': setting 'options' (file /etc/dinit.d/early-testline 4): unknown option: invalid
```
would become:
```
dinit: Error in service description for 'early-test' (file /etc/dinit.d/early-test, line 1): badly formed line.
dinit: Error in service description for 'early-test': setting 'options' (file /etc/dinit.d/early-test, line 4): unknown option: invalid
```
after this change.
=> Fix bad formatting of line number when a service fails to load

src/control.cc
While on LE this works, on BE it copies the other four bytes into the uint32_t, resulting in a zero. This in turn results in a protocol error on those architectures.
=> Fix SVCDSCDIR replies on 64-bit big endian architectures

.github/workflows/meson_ci.yml
"pkg-config" is not installed by default and meson cannot find "libcap".
=> CI: Add "pkg-config` as dependency in Debian Meson CI

configure, src/shutdown.cc
I tested dinit on NetBSD as far as replacing /sbin/init with it and it works! FYI I packaged it for pkgsrc in sysutils/dinit
=> feat: add NetBSD as a supported platform, use case for PLATFORM test

src/tests/cptests/Makefile
Fix unresolved symbols to libcap functions.
=> fuzzer: Fix build when building with libcap

doc/manpages/dinit-service.5.m4, src/igr-tests/igr-runner.cc, src/igr-tests/svc-arg-consumer/scripts/consumer.sh, src/igr-tests/svc-arg-consumer/scripts/producer.sh, src/igr-tests/svc-arg-consumer/sd/boot, src/igr-tests/svc-arg-consumer/sd/consumer, src/igr-tests/svc-arg-consumer/sd/producer, src/includes/load-service.h
Seems useful for s6-log/vlogger based logging systems.
It includes a new test: `svc-arg-consumer`. I decide to add a new test for it instead of using `svc-arg` because of usage of `process` services, `boot` service and also dinitctl commands for testing.
Fixes #427 
=> dinit-service: Do parameter substitution in consumer-of

src/igr-tests/meson.build
=> meson: Add missing service arguments related tests

.cirrus.yml
FreeBSD 14.0-RELEASE is EOF([1]) and also removed from CirrusCI.
This commit fixes recent CI failure.
[1]: https://www.freebsd.org/security/unsupported/
=> CI: Update freebsd-14-0 to freebsd-14-2

src/includes/service-constants.h
This will avoid a null dereference when logging an error in those stages.
=> service-constants: Add error description for SET_CAPS and SET_PRIO execution stages

src/tests/cptests/meson.build
Similar to #437 but for meson build.
=> meson: Fix fuzzer build when building with libcap

doc/manpages/shutdown.8.m4, src/control.cc, src/dinit.cc, src/includes/service-constants.h, src/shutdown.cc
Adds a -k option to 'shutdown', analogous to that of systemd and OpenRC. Am daily driving this and it gets a nice speedup on reboot. Also tried to make the ifdef-ing out of shutdown code based on RB_* constants more consistent, so the user can clearly see which shutdown modes are supported (since kexec may not be available at compile time on very old environments).
The only real downside that I can see is if the user has neglected to load an image before calling 'reboot -k', then reboot will return -1 with EINVAL, init will exit and the kernel will panic. I can't see an easy way to avoid this, since we only find out that the user *has* remembered to load an image when we call reboot() and it doesn't return.
=> Add -k option to shutdown for kexec functionality

.github/workflows/regular_ci.yml
Ubuntu-20.04 is getting removed from GitHub CI and we need to move to newer version.
I hope there not be ASLR related bugs.
See https://github.com/actions/runner-images/issues/11101 for more details.
=> CI: Use ubuntu-24.04 for regular ci

configure
=> configure: fix passing "LDFLAGS_LIBCAP" as option

.github/workflows/regular_ci.yml
Since https://github.com/davmac314/dinit/commit/be6c06139ea553743e6eade1313dbe364f1d869c Linux builds use configure by default.
Spotted after #489 not checked by CI.
=> CI: run the workflows on configure changes
